# Development configuration - PostgreSQL only
# Backend and Frontend run natively for faster development

services:
  postgres:
    image: postgres:15-alpine
    container_name: janus2-postgres-dev
    environment:
      POSTGRES_DB: janus2
      POSTGRES_USER: janus
      POSTGRES_PASSWORD: janus_dev_password
    ports:
      - "15530:5432"  # Host:Container - PostgreSQL on 15530
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U janus -d janus2"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    name: janus2-postgres-dev-data
